// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTwCygIDQW6Jg_0dUIZJ-CKqbX69ThK2M',
    appId: '1:19294380273:web:1ceac8013bec2e96ec4950',
    messagingSenderId: '19294380273',
    projectId: 'water-where-ah',
    authDomain: 'water-where-ah.firebaseapp.com',
    storageBucket: 'water-where-ah.appspot.com',
    measurementId: 'G-0HXTB0QXBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtEq9Jz3Y_HzxTJDBILP1ryTZuGdVaYxk',
    appId: '1:19294380273:android:1420265a806e3435ec4950',
    messagingSenderId: '19294380273',
    projectId: 'water-where-ah',
    storageBucket: 'water-where-ah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJf2bjuABLun3bG7Z3-SkOVl5TzpqjFQ',
    appId: '1:19294380273:ios:776defb3f6380ce6ec4950',
    messagingSenderId: '19294380273',
    projectId: 'water-where-ah',
    storageBucket: 'water-where-ah.appspot.com',
    iosClientId: '19294380273-bt7405cdu8kam81fsm1j9jsvsvn0bso2.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterWhereAh',
  );
}
